GUIDANCE_INTERVAL=7
INITIAL_FACE_DETECTION_WAIT_TIME=3
MAX_ATTEMPTS_TO_GET_A_TARGET_POSITION =3
VALID_POSITIONS = ["top left", "top right", "bottom left", "bottom right", "center"]
REQUIRED_STABLE_FRAMES=30
EDGE_THRESHOLD=0.1